TOP=../..
include $(TOP)/configure/CONFIG

#----------------------------------------
#  Template files
#----------------------------------------

# Module templates
DB += ethercat_gui_analog_input_module.template
DB += ethercat_gui_analog_output_module.template
DB += ethercat_gui_digital_input_module.template
DB += ethercat_gui_digital_output_module.template
DB += ethercat_gui_power_supply_module.template

# Channel templates
DB += ethercat_gui_analog_output_channel.template
DB += ethercat_gui_digital_output_channel.template
DB += ethercat_gui_input_channel.template

#----------------------------------------

include $(TOP)/configure/RULES
